[package]
name = "read_vs_mmap_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.8.0"
rand = "0.8.5"
anyhow = { version = "1", features = ["backtrace"] }
scopeguard = "1.1.0"